[cartographer]
klipper_section: mcu cartographer
is_klipper_fw: false
action_command: git -C ~/cartographer_firmware pull
action_command: ~/cartographer_firmware/fw_update.sh

[rpi]
klipper_section: mcu rpi
action_command: make flash

[Octopus]
klipper_section: mcu
action_command: make flash /dev/serial/by-id/usb-Klipper_stm32f446xx_440057000251313133353932-if00
#quiet_command: enter_bootloader -u <YOUR_CANBUS_UUID>
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-Klipper_stm32f446xx_440057000251313133353932-if00
config_name: 

[H36]
klipper_section: mcu H36_combo
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 17df9281fbb8

[ToqueCAN]
klipper_section: mcu toquecan
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u c57e72b4e533  

